from typing import Callable

LEXICON_CATALOG: dict[str, str | Callable] = {
    'welcome_text': '<b>Ассортимент магазина PREMIONCE</b>\n\n'
                    'Сильному человеку требуется многокомпонентный арсенал для преобразования жизненной энергии в '
                    'материальные и духовные блага.\n\n'
                    'PREMIONCE STORE - это инструментарий с помощью которого Вы быстрее и качественнее '
                    'получаете результаты во всех сферах.\n\n'
                    '✨ Выбирайте из каталога то, что резонирует с Вами.\n\n'
                    'Посмотрите наш ассортимент по '
                    '<a href="https://telegra.ph/Assortiment-magazina-PREMIONCE-07-06">ссылке</a>',
    'back_to_catalog': '🔙 Назад',
    'item_info': lambda description, dosage, quantity, price: (
        f'<b>Описание</b>: {description}\n\n'
        f'<b>Дозировка</b>: {dosage}\n\n'
        f'<b>Кол-во</b>: {quantity}\n\n'
        f'<b>Стоимость</b>: {price}₽\n\n'
    ),
}

LEXICON_CATALOG_CATEGORIES: dict[str, str] = {
    "racetami": "🧠 Рацетамы",
    "holinergetiki": "⚡ Холинергики",
    "stimulators": "🚀 Стимуляторы / Дофаминергические",
    "neiroprotectors": "🛡️ Нейропротекторы",
    "adaptogeni": "⚖️ Адаптогены / Эндокринные модуляторы",
    "antidepressanti": "😌 Антидепрессанты / Анксиолитики",
    "metabolicheskie": "🔬 Метаболические / Другие",
}

LEXICON_RACETAMI_ITEMS: dict[str, str] = {
    'aniracetam': "Анирацетам (Aniracetam)",
    'phenylpiracetam_hydrazide': "Фенотропил-гидразид (Phenylpiracetam Hydrazide)",
    'pramiracetam': "Прамирацетам (Pramiracetam)",
    'fasoracetam': "Фасорацетам (Fasoracetam)",
    'coluracetam': "Колурацетам (Coluracetam)",
    'noopept': "Омберацетам (Noopept)",
    'back_to_catalog': "🔙 Назад"
}

LEXICON_HOLINERGETIKI_ITEMS: dict[str, str] = {
    'citicoline': "CDP-Холин (Citicoline)",
    'centrophenoxine': "Мефеноксат (Centrophenoxine)",
    'encephabol': "Пиритинол (Encephabol)",
    'back_to_catalog': "🔙 Назад"
}

LEXICON_STIMULATORES_ITEMS: dict[str, str] = {
    'ladasten': "Бромантан (Ladasten)",
    'enerion': "Сульбутиамин (Enerion)",
    'wakix': "Питолизант (Wakix)",
    'tesofensine': "Тесофензин (Tesofensine)",
    'back_to_catalog': "🔙 Назад"
}

LEXICON_NEIROPROTECTORS_ITEMS: dict[str, str] = {
    'dihexa': "Дигекса (Dihexa, спрей)",
    'osavampator': "TAK-653 (Osavampator, спрей)",
    'j-147': "J-147",
    'l-thp': "L-THP (левотетрагидропальматин)",
    'prl-8-53': "PRL-8-53",
    'unifiram': "Унифирам (Unifiram)",
    'back_to_catalog': "🔙 Назад"
}

LEXICON_ADAPTOGENI_ITEMS: dict[str, str] = {
    '7-oho': "7-OXO (7-KETO-DHEA)",
    'cycloastragenol': "Циклоастрагенол (Cycloastragenol)",
    'androxal': "Энкломифен (Androxal)",
    'aromasin': "Экземестан (Aromasin)",
    'mk-677': "Ибутаморен (MK-677)",
    'fareston': "Торемифен (Fareston)",
    'back_to_catalog': "🔙 Назад"
}

LEXICON_ANTIDEPRESSANTI_ITEMS: dict[str, str] = {
    '9-me-bc': "9-ME-BC",
    'd-phenylalanine': "D-Фенилаланин (D-Phenylalanine)",
    'nor-bni': "NOR-BNI (спрей)",
    'back_to_catalog': "🔙 Назад"
}

LEXICON_METABOLICHESKIE_ITEMS: dict[str, str] = {
    'aicar': "AICAR",
    'ketas': "Ибудиласт (Ketas)",
    'magnesium_l-threonate': "Магний L-треонат (Magnesium L-Threonate)",
    'nnmti': "NNMTI (5-AMINO-1MQ)",
    '4-dma-78-dhf': "Эутропофлавин (4'-DMA-7,8-DHF)",
    '78-dhf': "Тропофлавин (7,8-DHF)",
    'amino-tadalafil': "AMINO-TADALAFIL (WITH BIOPERINE)",
    'back_to_catalog': "🔙 Назад"
}

LEXICON_CATEGORIES_INFO = {
    'racetami': {
        'category_id': 1,
        'category_name': 'racetami',
        'description': "Рацетамы — класс ноотропов, улучшающих когнитивные функции, память и концентрацию за счёт модуляции нейротрансмиттеров, особенно ацетилхолина и глутамата.",
        'items': LEXICON_RACETAMI_ITEMS
    },
    'holinergetiki': {
        'category_id': 2,
        'category_name': 'holinergetiki',
        'description': "Холинергики — группа веществ, усиливающих синтез, высвобождение или активность ацетилхолина — ключевого нейромедиатора для памяти, обучения и когнитивных функций. Они улучшают нейропластичность и могут снижать возрастное ухудшение когнитивных способностей.",
        'items': LEXICON_HOLINERGETIKI_ITEMS
    },
    'stimulators': {
        'category_id': 3,
        'category_name': 'stimulators',
        'description': "Стимуляторы и дофаминергические вещества повышают энергию, мотивацию и концентрацию за счёт усиления активности дофамина, норадреналина и других возбуждающих нейротрансмиттеров. Они улучшают работоспособность, но требуют осторожности из-за возможного привыкания и побочных эффектов.",
        'items': LEXICON_STIMULATORES_ITEMS
    },
    'neiroprotectors': {
        'category_id': 4,
        'category_name': 'neiroprotectors',
        'description': "Нейропротекторы — соединения, защищающие нервные клетки от повреждений, окислительного стресса и нейродегенерации. Они способствуют долгосрочному здоровью мозга, улучшают устойчивость к нагрузкам и могут замедлять возрастные когнитивные изменения.",
        'items': LEXICON_NEIROPROTECTORS_ITEMS
    },
    'adaptogeni': {
        'category_id': 5,
        'category_name': 'adaptogeni',
        'description': "Адаптогены и эндокринные модуляторы помогают организму адаптироваться к стрессу, нормализуя работу гормональной системы (кортизол, серотонин, мелатонин). Они улучшают устойчивость к нагрузкам, снижают усталость и способствуют балансу нервной системы.",
        'items': LEXICON_ADAPTOGENI_ITEMS
    },
    'antidepressanti': {
        'category_id': 6,
        'category_name': 'antidepressanti',
        'description': "Антидепрессанты и анксиолитики влияют на серотонин, ГАМК и другие нейромедиаторы, снижая тревожность, улучшая настроение и стабилизируя эмоциональный фон. Некоторые из них обладают ноотропными свойствами, улучшая когнитивные функции при стрессе.",
        'items': LEXICON_ANTIDEPRESSANTI_ITEMS
    },
    'metabolicheskie': {
        'category_id': 7,
        'category_name': 'metabolicheskie',
        'description': "Метаболические ноотропы и другие вещества улучшают энергообмен в мозге, усиливают кровообращение или оказывают комплексное воздействие на когнитивные функции. Они могут включать витаминоподобные соединения, пептиды и другие вспомогательные компоненты для поддержки работы мозга.",
        'items': LEXICON_METABOLICHESKIE_ITEMS
    }
}

LEXICON_ITEMS: dict[str, dict[str, int | str]] = {
    "7-oho": {
        "item_id": 1,
        "category_id": 5,
        "category_name": "adaptogeni",
        "name": "7-OXO (7-KETO-DHEA)",
        "price": 3400,
        "quantity": "30 капсул",
        "dosage": "100 мг",
        "description": "7-OXO (7-KETO-DHEA) - Ускоряет метаболизм, повышает энергию. Не влияет на гормоны напрямую.",
        "more_url": "https://telegra.ph/7-OXO-7-KETO-DHEA-by-PREMIONCE-03-10",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW0GiPei8KDDxtJ6nzK088-8XxOYE6AAJF8zEbXqCBSO3iPX4KoE5gAQADAgADeQADNgQ",
        "is_available": True,
    },
    "9-me-bc": {
        "item_id": 2,
        "category_id": 6,
        "category_name": "antidepressanti",
        "name": "9-ME-BC",
        "price": 1500,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "9-ME-BC - Восстанавливает дофаминовые нейроны. Улучшает мотивацию и когнитивные функции.",
        "more_url": "https://telegra.ph/9-ME-BC-by-PREMIONCE-05-25",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW0WiPeni2LDeH3T_OuJhFTUuvgfMCAAJH8zEbXqCBSMB1RupifOFvAQADAgADeQADNgQ",
        "is_available": True,
    },
    "aicar": {
        "item_id": 3,
        "category_id": 7,
        "category_name": "metabolicheskie",
        "name": "AICAR",
        "price": 1500,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "AICAR - Активирует AMPK, улучшает выносливость и метаболизм глюкозы.",
        "more_url": "https://telegra.ph/AICAR-by-PREMIONCE-07-06",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIMVGf60QnrFLy_vDZrTkzsgbR0e80SAAJ-9jEbJJvYS2Bnqm4gPLHkAQADAgADeAADNgQ",
        "is_available": True,
    },
    "amino-tadalafil": {
        "item_id": 4,
        "category_id": 7,
        "category_name": "metabolicheskie",
        "name": "AMINO-TADALAFIL (WITH BIOPERINE)",
        "price": 1600,
        "quantity": "60 капсул",
        "dosage": "5+5 мг",
        "description": "AMINO-TADALAFIL (WITH BIOPERINE) - Комбинация тадалафила и биоперина. Улучшает кровообращение и либидо.",
        "more_url": "https://telegra.ph/Amino-Tadalafil-by-PREMIONCE-05-17",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW0miPeru3AbxtBopLqpmS5XWMUuGxAAJJ8zEbXqCBSJGhgWe9CY_XAQADAgADeQADNgQ",
        "is_available": True,
    },
    "aniracetam": {
        "item_id": 5,
        "category_id": 1,
        "category_name": "aniracetam",
        "name": "ANIRACETAM",
        "price": 1400,
        "quantity": "30 капсул",
        "dosage": "300 мг",
        "description": "ANIRACETAM - Улучшает память и настроение, снижает тревожность. Действует через AMPA-рецепторы.",
        "more_url": "https://telegra.ph/ANIRACETAM-by-PREMIONCE-01-27",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW02iPes1ECtXTSmooHnPZXI4rcIkcAAJK8zEbXqCBSMbj1O_n81mqAQADAgADeQADNgQ",
        "is_available": True,
    },
    "ladasten": {
        "item_id": 6,
        "category_id": 3,
        "category_name": "stimulators",
        "name": "BROMANTANE (LADASTEN)",
        "price": 2500,
        "quantity": "30 капсул",
        "dosage": "50 мг",
        "description": "BROMANTANE (LADASTEN) - Повышает выносливость и адаптацию к стрессу. Без перевозбуждения.",
        "more_url": "https://telegra.ph/BROMANTANE-by-PREMIONCE-06-29",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIMVGf60QnrFLy_vDZrTkzsgbR0e80SAAJ-9jEbJJvYS2Bnqm4gPLHkAQADAgADeAADNgQ",
        "is_available": True,
    },
    "citicoline": {
        "item_id": 7,
        "category_id": 2,
        "category_name": "holinergetiki",
        "name": "CDP-CHOLINE (CITICOLINE)",
        "price": 1600,
        "quantity": "30 капсул",
        "dosage": "250 мг",
        "description": "CDP-CHOLINE (CITICOLINE) - Восстанавливает мембраны нейронов, улучшает фокус и ясность ума.",
        "more_url": "https://telegra.ph/CDP-CHOLINE-Citikolin-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW1GiPev8k83AZvy1n4Ak8bTqSG8bAAAJL8zEbXqCBSDYx5BeWjcS4AQADAgADeQADNgQ",
        "is_available": True,
    },
    "coluracetam": {
        "item_id": 8,
        "category_id": 1,
        "category_name": "racetami",
        "name": "COLURACETAM",
        "price": 2600,
        "quantity": "30 капсул",
        "dosage": "50 мг",
        "description": "COLURACETAM - Улучшает зрительное восприятие и память. Потенциальный антидепрессант.",
        "more_url": "https://telegra.ph/COLURACETAM-Koluracetam-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW1WiPexzAts44-cyzohF8BUcTvqJ1AAJP8zEbXqCBSGOAVKdgjvnYAQADAgADeQADNgQ",
        "is_available": True,
    },
    "cycloastragenol": {
        "item_id": 9,
        "category_id": 5,
        "category_name": "adaptogeni",
        "name": "CYCLOASTRAGENOL",
        "price": 3200,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "CYCLOASTRAGENOL - Активирует теломеразу, замедляет старение. Улучшает иммунитет.",
        "more_url": "https://telegra.ph/Cycloastragenol-by-PREMIONCE-03-10",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW1miPeyx8muS8RP0Yp9LnWiIJWsJ1AAJQ8zEbXqCBSBK7Gbpl0r4ZAQADAgADeQADNgQ",
        "is_available": True,
    },
    "d-phenylalanine": {
        "item_id": 10,
        "category_id": 6,
        "category_name": "antidepressanti",
        "name": "D-PHENYLALANINE",
        "price": 1400,
        "quantity": "30 капсул",
        "dosage": "700 мг",
        "description": "D-PHENYLALANINE - Повышает уровень эндорфинов. Эффективен при депрессии и боли.",
        "more_url": "https://telegra.ph/D-PHENYLALANINE-by-PREMIONCE-05-25",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW12iPezsGdlE0WuT46YrkgBC7S96UAAJR8zEbXqCBSDisWandpZy8AQADAgADeQADNgQ",
        "is_available": True,
    },
    "dihexa": {
        "item_id": 11,
        "category_id": 4,
        "category_name": "neiroprotectors",
        "name": "DIHEXA (SPRAY)",
        "price": 5500,
        "quantity": "100 мг в 5 мл",
        "dosage": "1 мг/пшик (100 доз)",
        "description": "DIHEXA (SPRAY) - Мощный нейрорегенератор, улучшает память и обучаемость.",
        "more_url": "https://telegra.ph/DIHEXA-Digeksa-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW2GiPe9VAyyvrXqdJCzW-WzOldNF8AAJT8zEbXqCBSPu70dJPLEF7AQADAgADeQADNgQ",
        "is_available": True,
    },
    "androxal": {
        "item_id": 12,
        "category_id": 5,
        "category_name": "adaptogeni",
        "name": "ENCLOMIPHENE (ANDROXAL)",
        "price": 2800,
        "quantity": "30 капсул",
        "dosage": "20 мг",
        "description": "ENCLOMIPHENE (ANDROXAL) - Повышает тестостерон, улучшает либидо и энергию.",
        "more_url": "https://telegra.ph/ENCLOMIPHENE-EHnklomifen-Androksal-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW2WiPe-_7sq-21sbJp_jWzQTzmC_HAAJU8zEbXqCBSD2quU5LiZV_AQADAgADeQADNgQ",
        "is_available": True,
    },
    "4-dma-78-dhf": {
        "item_id": 13,
        "category_id": 7,
        "category_name": "metabolicheskie",
        "name": "EUTROPOFLAVIN (4'-DMA-7,8-DHF)",
        "price": 2200,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "EUTROPOFLAVIN (4'-DMA-7,8-DHF) - Аналог BDNF, улучшает нейропластичность и память.",
        "more_url": "https://telegra.ph/Eutropoflavin-4-DMA-78-DHF-by-PREMIONCE-03-10",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW2miPfAABlwVXoS7xGtyN09Nkkr-99QACVfMxG16ggUgF73ilQUglcwEAAwIAA3kAAzYE",
        "is_available": True,
    },
    "aromasin": {
        "item_id": 14,
        "category_id": 5,
        "category_name": "adaptogeni",
        "name": "EXEMESTANE (AROMASIN)",
        "price": 1800,
        "quantity": "30 капсул",
        "dosage": "25 мг",
        "description": "EXEMESTANE (AROMASIN) - Ингибитор ароматазы. Снижает эстроген, повышает тестостерон.",
        "more_url": "https://telegra.ph/EXEMESTANE-Aromazin-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW22iPfBsRhbQB4nlQ1G696sDwt5BdAAJY8zEbXqCBSKnD-WXjdeuIAQADAgADeQADNgQ",
        "is_available": True,
    },
    "fasoracetam": {
        "item_id": 15,
        "category_id": 1,
        "category_name": "racetami",
        "name": "FASORACETAM",
        "price": 2600,
        "quantity": "30 капсул",
        "dosage": "100 мг",
        "description": "FASORACETAM - Улучшает внимание и обучаемость, особенно при СДВГ.",
        "more_url": "https://telegra.ph/FASORACETAM-by-PREMIONCE-01-27",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIMVGf60QnrFLy_vDZrTkzsgbR0e80SAAJ-9jEbJJvYS2Bnqm4gPLHkAQADAgADeAADNgQ",
        "is_available": True,
    },
    "ketas": {
        "item_id": 16,
        "category_id": 7,
        "category_name": "metabolicheskie",
        "name": "IBUDILAST (KETAS)",
        "price": 2000,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "IBUDILAST (KETAS) - нейропротектор, снижает нейровоспаление.",
        "more_url": "https://telegra.ph/IBUDILAST-by-PREMIONCE-01-27",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW3GiPfEieW1TlXthjkiyAollOWYL9AAJb8zEbXqCBSDXVs75wcchlAQADAgADeQADNgQ",
        "is_available": True,
    },
    "mk-677": {
        "item_id": 17,
        "category_id": 5,
        "category_name": "adaptogeni",
        "name": "IBUTAMOREN (MK-677)",
        "price": 2000,
        "quantity": "30 капсул",
        "dosage": "15 мг",
        "description": "IBUTAMOREN (MK-677) - Стимулятор гормона роста. Увеличивает мышечную массу.",
        "more_url": "https://telegra.ph/IBUTAMOREN-MK-677-by-PREMIONCE-01-27",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW3WiPfFy-Xe3cuU1vQ_KtkAnzjxUAA2LzMRteoIFIepSotu21RggBAAMCAAN5AAM2BA",
        "is_available": True,
    },
    "j-147": {
        "item_id": 18,
        "category_id": 4,
        "category_name": "neiroprotectors",
        "name": "J-147",
        "price": 1600,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "J-147 - Антиоксидант и нейропротектор, замедляет старение мозга.",
        "more_url": "https://telegra.ph/J-147-by-PREMIONCE-06-22",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW3miPfJyhyhCS1JPhhaBfPPNUvwg1AAJk8zEbXqCBSC9JyR6uUGIdAQADAgADeQADNgQ",
        "is_available": True,
    },
    "l-thp": {
        "item_id": 19,
        "category_id": 4,
        "category_name": "neiroprotectors",
        "name": "L-THP",
        "price": 1200,
        "quantity": "30 капсул",
        "dosage": "30 мг",
        "description": "L-THP - Анксиолитик и мягкий стимулятор. Снижает тревожность.",
        "more_url": "https://telegra.ph/L-THP-L-Tetrahydropalmatine-by-PREMIONCE-03-10",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW32iPfKt3QxjGOXh2RKss27r1DcdsAAJl8zEbXqCBSBfNKrpn2geuAQADAgADeQADNgQ",
        "is_available": True,
    },
    "magnesium_l-threonate": {
        "item_id": 20,
        "category_id": 7,
        "category_name": "metabolicheskie",
        "name": "MAGNESIUM L-THREONATE",
        "price": 1000,
        "quantity": "30 капсул",
        "dosage": "500 мг",
        "description": "MAGNESIUM L-THREONATE - Лучшая форма магния для мозга. Улучшает память и сон.",
        "more_url": "https://telegra.ph/MAGNESIUM-L-THREONATE-by-PREMIONCE-06-29",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIMVGf60QnrFLy_vDZrTkzsgbR0e80SAAJ-9jEbJJvYS2Bnqm4gPLHkAQADAgADeAADNgQ",
        "is_available": True,
    },
    "centrophenoxine": {
        "item_id": 21,
        "category_id": 2,
        "category_name": "holinergetiki",
        "name": "MECLOFENOXATE (CENTROPHENOXINE)",
        "price": 3500,
        "quantity": "30 капсул",
        "dosage": "300 мг",
        "description": "MECLOFENOXATE (CENTROPHENOXINE) - Улучшает энергетический обмен в мозге, замедляет старение.",
        "more_url": "https://telegra.ph/Meclofenoxate-Centrophenoxine-by-PREMIONCE-03-10",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW5GiPfO67TYqsIfDY-FZb_ZJnrwV-AAJn8zEbXqCBSBhDx1dLnJA1AQADAgADeQADNgQ",
        "is_available": True,
    },
    "nnmti": {
        "item_id": 22,
        "category_id": 7,
        "category_name": "metabolicheskie",
        "name": "NNMTI (5-AMINO-1MQ)",
        "price": 5700,
        "quantity": "30 капсул",
        "dosage": "50 мг",
        "description": "NNMTI (5-AMINO-1MQ) - Блокирует NNMT, повышает NAD+. Замедляет старение.",
        "more_url": "https://telegra.ph/NNMTi-5-amino-1MQ-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW5WiPfPxx_zAxYd2RK0Yh_WZidSmfAAJo8zEbXqCBSH91zLH1Cov2AQADAgADeQADNgQ",
        "is_available": True,
    },
    "nor-bni": {
        "item_id": 23,
        "category_id": 6,
        "category_name": "antidepressanti",
        "name": "NOR-BNI",
        "price": 3800,
        "quantity": "50 мг в 10 мл",
        "dosage": "750 мкг/пшик (65 доз)",
        "description": "NOR-BNI - Блокирует каппа-опиоидные рецепторы, снижает тревожность.",
        "more_url": "https://telegra.ph/NOR-BNI-Norbinaltorphimine-by-PREMIONCE-01-27",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW5miPfQiocUsRoGHhgYaXCNoqjLKLAAJp8zEbXqCBSKTWMkgkX2WfAQADAgADeQADNgQ",
        "is_available": True,
    },
    "noopept": {
        "item_id": 24,
        "category_id": 1,
        "category_name": "racetami",
        "name": "OMBERACETAM (NOOPEPT)",
        "price": 1200,
        "quantity": "30 капсул",
        "dosage": "30 мг",
        "description": "OMBERACETAM (NOOPEPT) - Нейропротектор с анксиолитическим эффектом.",
        "more_url": "https://telegra.ph/OMBERACETAM-Omberacetam-Noopept-by-PREMIONCE-01-27",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW52iPfRyYJkv3Evel3Rxn5Wo4gq4QAAJq8zEbXqCBSNpfuoz6tKtyAQADAgADeQADNgQ",
        "is_available": True,
    },
    "phenylpiracetam_hydrazide": {
        "item_id": 25,
        "category_id": 1,
        "category_name": "racetami",
        "name": "PHENYLPIRACETAM HYDRAZIDE",
        "price": 2500,
        "quantity": "30 капсул",
        "dosage": "100 мг",
        "description": "PHENYLPIRACETAM HYDRAZIDE - Аналог фенотропила с пролонгированным действием.",
        "more_url": "https://telegra.ph/PREMIZIDE-Phenylpiracetam-hydrazide-by-PREMIONCE-01-27",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW6GiPfTly3K0nIhfv3oIdbE3zw6mSAAJr8zEbXqCBSM_Xt8ByAzRTAQADAgADeQADNgQ",
        "is_available": True,
    },
    "wakix": {
        "item_id": 26,
        "category_id": 3,
        "category_name": "stimulators",
        "name": "PITOLISANT (WAKIX)",
        "price": 3500,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "PITOLISANT (WAKIX) - Блокирует гистаминовые рецепторы, повышает бодрость.",
        "more_url": "https://telegra.ph/PITOLISANT-WAKIX-by-PREMIONCE-07-06",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIMVGf60QnrFLy_vDZrTkzsgbR0e80SAAJ-9jEbJJvYS2Bnqm4gPLHkAQADAgADeAADNgQ",
        "is_available": True,
    },
    "pramiracetam": {
        "item_id": 27,
        "category_id": 1,
        "category_name": "racetami",
        "name": "PRAMIRACETAM",
        "price": 2500,
        "quantity": "30 капсул",
        "dosage": "300 мг",
        "description": "PRAMIRACETAM - Сильный стимулятор памяти и аналитического мышления.",
        "more_url": "https://telegra.ph/PRAMIRACETAM-by-PREMIONCE-01-27",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW6WiPfVFjE4nH39xbqVZopMnzbnsOAAJs8zEbXqCBSI68dnfhN-k0AQADAgADeQADNgQ",
        "is_available": True,
    },
    "prl-8-53": {
        "item_id": 28,
        "category_id": 4,
        "category_name": "neiroprotectors",
        "name": "PRL-8-53",
        "price": 1400,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "PRL-8-53 - Улучшает краткосрочную память. Эффект после однократного приема.",
        "more_url": "https://telegra.ph/PRL-8-53-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW6miPfWBqQ1o0n6oUw0Pli159oVe6AAJt8zEbXqCBSHCDAwlmr2a6AQADAgADeQADNgQ",
        "is_available": True,
    },
    "encephabol": {
        "item_id": 29,
        "category_id": 2,
        "category_name": "holinergetiki",
        "name": "PYRITINOL (ENCEFABOL)",
        "price": 2000,
        "quantity": "30 капсул",
        "dosage": "100 мг",
        "description": "PYRITINOL (ENCEFABOL) - Стимулирует метаболизм глюкозы в мозге. Повышает бодрость.",
        "more_url": "https://telegra.ph/Pyritinol-Pyrithioxine-by-PREMIONCE-03-10",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW62iPfW0xrWiNG5YrctV6m97_Bn81AAJu8zEbXqCBSJIr4q1dmGvUAQADAgADeQADNgQ",
        "is_available": True,
    },
    "enerion": {
        "item_id": 30,
        "category_id": 3,
        "category_name": "stimulators",
        "name": "SULBUTIAMINE (ENERION)",
        "price": 1800,
        "quantity": "30 капсул",
        "dosage": "200 мг",
        "description": "SULBUTIAMINE (ENERION) - Улучшает энергетический обмен, снижает усталость.",
        "more_url": "https://telegra.ph/Sulbutiamine-by-PREMIONCE-03-10",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW7GiPfYMDOPoGsMO1N7ZhbzyQfAYHAAJw8zEbXqCBSGkAAab_VP8P5QEAAwIAA3kAAzYE",
        "is_available": True,
    },
    "osavampator": {
        "item_id": 31,
        "category_id": 4,
        "category_name": "neiroprotectors",
        "name": "TAK-653 (OSAVAMPATOR)",
        "price": 3000,
        "quantity": "100 мг в 5 мл DMSO",
        "dosage": "1 мг/пшик (100 доз)",
        "description": "TAK-653 (OSAVAMPATOR) - Усиливает синаптическую пластичность через AMPA-рецепторы.",
        "more_url": "https://telegra.ph/TAK-653-Osavampator-by-PREMIONCE-06-22",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW7WiPfZC2MYue0MGHQvB_T3u9BGJSAAJx8zEbXqCBSCQMjAIeRkIaAQADAgADeQADNgQ",
        "is_available": True,
    },
    "tesofensine": {
        "item_id": 32,
        "category_id": 3,
        "category_name": "stimulators",
        "name": "TESOFENSINE",
        "price": 3000,
        "quantity": "30 мг в 3 мл DMSO",
        "dosage": "500 мкг/пшик (60 доз)",
        "description": "TESOFENSINE - Сильный ингибитор обратного захвата дофамина и норадреналина.",
        "more_url": "https://telegra.ph/TESO-Tesofensine-by-PREMIONCE-03-10",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW7miPfZwqdL5VE4yhqkafwTRqVQ0kAAJy8zEbXqCBSF5inPDEpfGuAQADAgADeQADNgQ",
        "is_available": True,
    },
    "fareston": {
        "item_id": 33,
        "category_id": 5,
        "category_name": "adaptogeni",
        "name": "TOREMIFEN (FARESTON)",
        "price": 3500,
        "quantity": "30 капсул",
        "dosage": "20 мг",
        "description": "TOREMIFEN (FARESTON) - Антиэстроген, используется в терапии рака груди.",
        "more_url": "https://telegra.ph/Toremifene-Fareston-by-PREMIONCE-05-17",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW72iPfarggLeG3_JYjTk1K-41gB18AAJ08zEbXqCBSKJtap0QKUNFAQADAgADeQADNgQ",
        "is_available": True,
    },
    "78-dhf": {
        "item_id": 34,
        "category_id": 7,
        "category_name": "metabolicheskie",
        "name": "TROPOFLAVIN (7,8-DHF)",
        "price": 1300,
        "quantity": "30 капсул",
        "dosage": "25 мг",
        "description": "TROPOFLAVIN (7,8-DHF) - Усиливает когнитивные функции, защищает нейроны.",
        "more_url": "https://telegra.ph/TROPOFLAVIN-78-DHF-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW8GiPfbdYc8LL2K4f2Xta-oVYzmUsAAJ18zEbXqCBSCzgniTCsDR0AQADAgADeQADNgQ",
        "is_available": True,
    },
    "unifiram": {
        "item_id": 35,
        "category_id": 7,
        "category_name": "metabolicheskie",
        "name": "UNIFIRAM",
        "price": 2800,
        "quantity": "30 капсул",
        "dosage": "10 мг",
        "description": "UNIFIRAM - Усиливает когнитивные функции, может улучшать долговременную память.",
        "more_url": "https://telegra.ph/UNIFIRAM-Unifiram-by-PREMIONCE-10-30",
        "stock": 100,
        "image_url": "AgACAgIAAxkBAAIW8WiPfcobBpZgHeLWs5tNITme0IHjAAJ38zEbXqCBSOV9mw-SAAF-owEAAwIAA3kAAzYE",
        "is_available": True,
    }
}
